"""Create route_logs table

Revision ID: 5ed692ada803
Revises: 
Create Date: 2025-12-19 06:48:52.344259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed692ada803'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('route_path', sa.String(), nullable=False),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_query_params', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('error_type', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_logs_duration', 'route_logs', ['duration_ms'], unique=False)
    op.create_index('idx_route_logs_route_path', 'route_logs', ['route_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_route_logs_route_path', table_name='route_logs')
    op.drop_index('idx_route_logs_duration', table_name='route_logs')
    op.drop_table('route_logs')
    # ### end Alembic commands ###
